sudo: required
language: node_js
node_js:
  - "0.10"
before_install:
  - "curl -L https://raw.githubusercontent.com/AXV-Against-Extreme-Violence/meteor-velocity-travis-ci/master/configure.sh | /bin/sh"
